Basic CLI Implementation 2
sethitow/stc pull request #4
Opened 2021-07-29 23:37 UTC by MaxIsWell42

2021-07-29 23:47 UTC, sethitow requested changes
Please remove `.DS_Store`, `stc`, `main`, and `example` binary files from source control.

Because a new library (Boost) is used in your changes, you’ll need to edit `ci.yml` in order for builds to pass. This will involve adding a new build step that runs `apt-get install libboost-all-dev`. You’ll also need to lower the minimum required Boost version in CMakeLists.txt

2021-07-31 19:20 UTC, MaxIsWell42 commented
> Please remove `.DS_Store`, `stc`, `main`, and `example` binary files from source control.
> 
> Because a new library (Boost) is used in your changes, you’ll need to edit `ci.yml` in order for builds to pass. This will involve adding a new build step that runs `apt-get install libboost-all-dev`. You’ll also need to lower the minimum required Boost version in CMakeLists.txt

Made these changes. Set boost version to need to be at least 1.7.0 instead of 1.7.6, but still can't find .DS_Store even when  viewing hidden files.

2021-08-03 18:25 UTC, sethitow requested changes
Please squash commits, and I think we’re good to merge!

2021-08-03 18:25 UTC, sethitow commented on src/compile.hpp
> +#include <iostream>
`iostream` doesn’t need to be included here
```suggestion
```

2021-08-03 18:25 UTC, sethitow commented on src/parse.hpp
> +#include <iostream>
`iostream` doesn’t need to be included here
```suggestion
```

2021-08-04 23:05 UTC, sethitow approved these changes

2021-08-04 23:06 UTC, merged